# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('email_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=45, null=True)),
                ('picture_url', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
