# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testingSite', '0004_postdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('meter_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('min_date', models.DateTimeField(blank=True, null=True)),
                ('min_val', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('max_date', models.DateTimeField(blank=True, null=True)),
                ('max_val', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('curr_val', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('avg_val', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HourlyWiseStats',
            fields=[
                ('stats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testingSite.Stats')),
            ],
            options={
                'managed': True,
            },
            bases=('testingSite.stats',),
        ),
    ]
